image: "rust:latest"

before_script:
    - 
    - rustup toolchain add nightly
    - rustup target add x86_64-unknown-redox --toolchain nightly
    - rustup show      # Print version info for debugging

build:linux:
    script:
        - make all

#build:redox:
#    script:
#        - make all

test:linux:
    script:
        - make test

fmt:
    script:
        - ./fmt.sh -- --write-mode=diff

# TODO: Set up a docker image with a redox vm that would allow to
#   run things like tests under redox