language: rust
env:
  -
  - TARGET=aarch64-unknown-linux-gnu
  - TARGET=x86_64-unknown-redox
rust:
  - nightly
before_script:
  - rustup component add rustfmt-preview
  - if [ -n "$TARGET" ]; then rustup target add $TARGET; fi
script:
  - ./ci.sh
notifications:
  email: false
