[package]
name = "relibc"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[lib]
name = "c"
crate-type = ["staticlib"]

[workspace]

[dependencies]
fcntl = { path = "fcntl" }
unistd = { path = "unistd" }

[profile.dev]
incremental = false
lto = true
panic = "abort"

[profile.release]
incremental = false
lto = true
panic = "abort"
