[package]
name = "relibc"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[lib]
name = "c"
crate-type = ["staticlib"]

[workspace]
members = ["crt0"]

[dependencies]
compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins.git", default-features = false, features = ["mem"] }
platform = { path = "platform" }
fcntl = { path = "src/fcntl" }
stdio = { path = "src/stdio" }
stdlib = { path = "src/stdlib" }
string = { path = "src/string" }
unistd = { path = "src/unistd" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
