[package]
name = "unistd"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
build = "build.rs"

[build-dependencies]
cbindgen = "0.5"

[dependencies]
common = { path = "../common" }
